// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQbXocJcuz-kW57anCZCem_aJUYDmp-Q',
    appId: '1:695372437143:web:1b8e53627546d9f4ebfbd2',
    messagingSenderId: '695372437143',
    projectId: 'learn-auth-lesson-1',
    authDomain: 'learn-auth-lesson-1.firebaseapp.com',
    databaseURL: 'https://learn-auth-lesson-1-default-rtdb.firebaseio.com',
    storageBucket: 'learn-auth-lesson-1.appspot.com',
    measurementId: 'G-RDSXS1F749',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQm-KbWUHXCCg895yOJWci3S8SnsHHVg',
    appId: '1:695372437143:android:f52b90e433672e2debfbd2',
    messagingSenderId: '695372437143',
    projectId: 'learn-auth-lesson-1',
    databaseURL: 'https://learn-auth-lesson-1-default-rtdb.firebaseio.com',
    storageBucket: 'learn-auth-lesson-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pVuXlGndwkqKjjbRiM9pZ9SBS4jw7tI',
    appId: '1:695372437143:ios:16992b9b1e966e49ebfbd2',
    messagingSenderId: '695372437143',
    projectId: 'learn-auth-lesson-1',
    databaseURL: 'https://learn-auth-lesson-1-default-rtdb.firebaseio.com',
    storageBucket: 'learn-auth-lesson-1.appspot.com',
    iosBundleId: 'com.example.learnFirebaseStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-pVuXlGndwkqKjjbRiM9pZ9SBS4jw7tI',
    appId: '1:695372437143:ios:16992b9b1e966e49ebfbd2',
    messagingSenderId: '695372437143',
    projectId: 'learn-auth-lesson-1',
    databaseURL: 'https://learn-auth-lesson-1-default-rtdb.firebaseio.com',
    storageBucket: 'learn-auth-lesson-1.appspot.com',
    iosBundleId: 'com.example.learnFirebaseStorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQbXocJcuz-kW57anCZCem_aJUYDmp-Q',
    appId: '1:695372437143:web:766e83eaec4b37a0ebfbd2',
    messagingSenderId: '695372437143',
    projectId: 'learn-auth-lesson-1',
    authDomain: 'learn-auth-lesson-1.firebaseapp.com',
    databaseURL: 'https://learn-auth-lesson-1-default-rtdb.firebaseio.com',
    storageBucket: 'learn-auth-lesson-1.appspot.com',
    measurementId: 'G-542P02P53D',
  );
}
